In [1]:
import cv2
import numpy as np

In [2]:
lena_ori = cv2.imread("image/lena.png")
cv2.imshow("Original", lena_ori)
cv2.waitKey(0)
cv2.destroyAllWindows()

### change saturation
HLS color space －> change s channel

In [3]:
# [Hue, Lightness, Saturation]
lena_hls = cv2.cvtColor(lena_ori, cv2.COLOR_BGR2HLS)
lena_hls

array([[[  4, 176, 162],
        [  4, 176, 162],
        [  1, 178, 149],
        ...,
        [  7, 176, 174],
        [  5, 166, 158],
        [  2, 145, 128]],

       [[  4, 176, 162],
        [  4, 176, 162],
        [  1, 178, 149],
        ...,
        [  7, 176, 174],
        [  5, 166, 158],
        [  2, 145, 128]],

       [[  4, 176, 162],
        [  4, 176, 162],
        [  1, 178, 149],
        ...,
        [  7, 176, 174],
        [  5, 166, 158],
        [  2, 145, 128]],

       ...,

       [[161,  51, 165],
        [161,  51, 165],
        [166,  60, 139],
        ...,
        [177, 123, 104],
        [178, 120, 110],
        [176, 120, 123]],

       [[162,  52, 147],
        [162,  52, 147],
        [166,  64, 128],
        ...,
        [178, 124, 112],
        [177, 126, 111],
        [178, 130, 113]],

       [[162,  52, 147],
        [162,  52, 147],
        [166,  64, 128],
        ...,
        [178, 124, 112],
        [177, 126, 111],
        [178, 130, 113]]

In [4]:
lena_hls[:,:,-1]

array([[162, 162, 149, ..., 174, 158, 128],
       [162, 162, 149, ..., 174, 158, 128],
       [162, 162, 149, ..., 174, 158, 128],
       ...,
       [165, 165, 139, ..., 104, 110, 123],
       [147, 147, 128, ..., 112, 111, 113],
       [147, 147, 128, ..., 112, 111, 113]], dtype=uint8)

In [5]:
change_percentage = 0.2

lena_hls_down = lena_hls.astype('float32')
lena_hls_down[:,:, -1] = lena_hls_down[:,:, -1]/255 - change_percentage
lena_hls_down[lena_hls_down[:,:, -1] < 0] = 0
lena_hls_down[:,:, -1] = np.round(lena_hls_down[:,:, -1] * 255)
lena_hls_down

array([[[  4., 176., 111.],
        [  4., 176., 111.],
        [  1., 178.,  98.],
        ...,
        [  7., 176., 123.],
        [  5., 166., 107.],
        [  2., 145.,  77.]],

       [[  4., 176., 111.],
        [  4., 176., 111.],
        [  1., 178.,  98.],
        ...,
        [  7., 176., 123.],
        [  5., 166., 107.],
        [  2., 145.,  77.]],

       [[  4., 176., 111.],
        [  4., 176., 111.],
        [  1., 178.,  98.],
        ...,
        [  7., 176., 123.],
        [  5., 166., 107.],
        [  2., 145.,  77.]],

       ...,

       [[161.,  51., 114.],
        [161.,  51., 114.],
        [166.,  60.,  88.],
        ...,
        [177., 123.,  53.],
        [178., 120.,  59.],
        [176., 120.,  72.]],

       [[162.,  52.,  96.],
        [162.,  52.,  96.],
        [166.,  64.,  77.],
        ...,
        [178., 124.,  61.],
        [177., 126.,  60.],
        [178., 130.,  62.]],

       [[162.,  52.,  96.],
        [162.,  52.,  96.],
        [166.,  

In [6]:
lena_hls_up = lena_hls.astype('float32')
lena_hls_up[..., -1] = lena_hls_up[..., -1]/255 + change_percentage
lena_hls_up[lena_hls_up[..., -1] > 1] = 1
lena_hls_up[..., -1] = np.round(lena_hls_up[:,:, -1] * 255)
lena_hls_up

array([[[  4., 176., 213.],
        [  4., 176., 213.],
        [  1., 178., 200.],
        ...,
        [  7., 176., 225.],
        [  5., 166., 209.],
        [  2., 145., 179.]],

       [[  4., 176., 213.],
        [  4., 176., 213.],
        [  1., 178., 200.],
        ...,
        [  7., 176., 225.],
        [  5., 166., 209.],
        [  2., 145., 179.]],

       [[  4., 176., 213.],
        [  4., 176., 213.],
        [  1., 178., 200.],
        ...,
        [  7., 176., 225.],
        [  5., 166., 209.],
        [  2., 145., 179.]],

       ...,

       [[161.,  51., 216.],
        [161.,  51., 216.],
        [166.,  60., 190.],
        ...,
        [177., 123., 155.],
        [178., 120., 161.],
        [176., 120., 174.]],

       [[162.,  52., 198.],
        [162.,  52., 198.],
        [166.,  64., 179.],
        ...,
        [178., 124., 163.],
        [177., 126., 162.],
        [178., 130., 164.]],

       [[162.,  52., 198.],
        [162.,  52., 198.],
        [166.,  

In [7]:
lena_bgr_down = cv2.cvtColor(lena_hls_down, cv2.COLOR_HLS2BGR)
lena_bgr_up = cv2.cvtColor(lena_hls_up, cv2.COLOR_HLS2BGR)

In [8]:
lena_change = np.hstack((lena_hls, lena_bgr_down, lena_bgr_up))
lena_change

array([[[ 4.0000000e+00,  1.7600000e+02,  1.6200000e+02],
        [ 4.0000000e+00,  1.7600000e+02,  1.6200000e+02],
        [ 1.0000000e+00,  1.7800000e+02,  1.4900000e+02],
        ...,
        [ 3.9551000e+04,  3.0363500e+04, -3.9199000e+04],
        [ 3.4651000e+04,  2.8903500e+04, -3.4319000e+04],
        [ 2.5921000e+04,  2.4202600e+04, -2.5631000e+04]],

       [[ 4.0000000e+00,  1.7600000e+02,  1.6200000e+02],
        [ 4.0000000e+00,  1.7600000e+02,  1.6200000e+02],
        [ 1.0000000e+00,  1.7800000e+02,  1.4900000e+02],
        ...,
        [ 3.9551000e+04,  3.0363500e+04, -3.9199000e+04],
        [ 3.4651000e+04,  2.8903500e+04, -3.4319000e+04],
        [ 2.5921000e+04,  2.4202600e+04, -2.5631000e+04]],

       [[ 4.0000000e+00,  1.7600000e+02,  1.6200000e+02],
        [ 4.0000000e+00,  1.7600000e+02,  1.6200000e+02],
        [ 1.0000000e+00,  1.7800000e+02,  1.4900000e+02],
        ...,
        [ 3.9551000e+04,  3.0363500e+04, -3.9199000e+04],
        [ 3.4651000e+04,  2.8

In [9]:
cv2.imshow("change saturation", lena_change)
cv2.waitKey(0)
cv2.destroyAllWindows()